[project]
title = "Avyukt's Preswald Project"
version = "0.1.0"
port = 8501
slug = "preswald-project"  
entrypoint = "hello.py"    

[branding]
name = "Avyukt's Project"
logo = "data/Avyukt.png"
favicon = "data/favicon.ico"
primaryColor = "#9ea6f0"
# primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

# created a new import, just like ("sample_csv")
[data.titanic_csv]
type = "csv"
path = "data/titanic.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"